//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Construct.rc
//
#define ID_OBJECTINFO                   1
#define ID_EDIT                         2
#define IDC_IMPORTFRAME                 2
#define IDEVAL                          3
#define ID_ADDCOLOUR                    3
#define IDOK2                           3
#define IDC_IMPORTANIMATION             3
#define IDOK3                           4
#define ID_CHANGEALLTO_FLASH            21
#define ID_CHANGEALLTO_GRID             22
#define ID_CHANGEALLTO_CHRONOLOGICAL    23
#define ID_CONDITIONS_ADDCONDITION      24
#define ID_APPEARANCE_XP                25
#define ID_APPEARANCE_2003              26
#define ID_APPEARANCE_2005              27
#define ID_BOOKMARK                     30
#define ID_REMOVEBOOKMARKS              31
#define ID_NEXTBOOKMARK                 32
#define ID_PREVIOUSBOOKMARK             33
#define IDD_ABOUTBOX                    100
#define IDS_TRUE                        100
#define IDS_FALSE                       101
#define IDB_AUTOPAN                     101
#define IDS_NOITEMSEL                   102
#define IDS_SELFORINFO                  103
#define IDR_MAINFRAME                   128
#define IDR_COLORSTYPE                  129
#define IDD_COLSEL                      129
#define ID_WEB_SCIRRA                   129
#define ID_WEB_SCIRRACOM                129
#define IDS_UPDATE                      130
#define IDS_TIME                        131
#define IDD_PREFER                      132
#define IDC_DRAGITEM                    132
#define ID_WEB_FORUMS                   132
#define IDD_OBJECT                      133
#define ID_WEB_REPORTBUG                133
#define IDD_INSERTOBJECTS               133
#define ID_WEB_HELP                     134
#define ID_WEB_UPDATE                   135
#define IDR_PROJWIN                     136
#define ID_WRAP                         136
#define IDC_PROPLIST                    137
#define IDD_PROPLIST                    137
#define IDB_BITMAP2                     138
#define ID_MASK                         139
#define IDB_PROJECT                     140
#define IDR_FRAMENO                     142
#define IDD_EXPRESSIONEDIT              142
#define IDD_SETTINGS_DLG                143
#define IDB_HAMMER                      149
#define IDD_PROPERTY_PAGE1              150
#define IDD_NEWTRIGGER                  150
#define IDD_EVENTWIZARD                 150
#define IDB_LOOPC                       151
#define IDR_RUNTIME                     151
#define IDD_COMMENT                     153
#define IDD_ECOMMENT                    153
#define IDD_PROPERTY_PAGE_2             154
#define IDD_SETTINGS_AUTOSAVE           154
#define IDD_VERIFICATION                155
#define IDB_WARNING                     156
#define IDD_MENUEDITOR                  157
#define IDD_REPORTBUG                   158
#define IDD_GETNIGHTLY                  159
#define IDB_UPDATE                      160
#define IDD_IMAGEBANK                   162
#define IDB_NOIMAGE                     163
#define IDD_EDITIMAGE                   164
#define IDR_ROTATION                    165
#define IDR_BLURS                       166
#define IDR_EFFECTS                     167
#define IDI_ICON1                       167
#define IDR_APPPROPS                    168
#define IDB_SMALL                       168
#define IDB_CROSS                       168
#define IDI_ICON2                       168
#define IDB_EVENT1                      169
#define IDB_BITMAP4                     169
#define IDD_LAYERBOX                    169
#define IDD_BARDIALOG                   169
#define IDR_TOOLS                       170
#define IDR_FRAMEEDITOR                 170
#define IDR_PIC_TOOLS                   170
#define IDR_LAYOUT                      170
#define IDR_BLANK                       171
#define IDR_FRAMETOOLS                  171
#define IDD_COLORS                      172
#define IDR_PARAM                       172
#define IDR_COMMENT                     172
#define IDB_STRING                      173
#define IDR_OBJECT                      173
#define IDD_TOOLS                       174
#define IDB_NUMBER                      174
#define IDR_FILTER1                     175
#define IDB_FIRSTSTART                  176
#define IDD_COLORMIXER                  177
#define IDC_PE_FILL                     177
#define IDD_ERROR                       178
#define IDB_DEFAULTTEX                  178
#define IDD_PARAMETERS                  179
#define IDD_OBJECTINFO                  180
#define IDD_ARRAYPASTE                  181
#define IDR_OBJECTTOOLBAR               181
#define IDR_SYSTEMTOOLBAR               182
#define IDD_FIRSTSTART                  183
#define IDR_CONDITIONTOOLBAR            183
#define IDD_SET_LANGUAGES               184
#define IDR_COMMENTMENU                 184
#define IDR_DEBUG                       185
#define IDD_COMPAREVALUES               186
#define IDD_ONFUNCTION                  186
#define IDB_CUSTOM                      187
#define IDB_DOT                         190
#define IDD_PALETTE                     192
#define IDD_BLANK                       193
#define IDD_NTEMPLATE                   196
#define IDR_PIC_MAIN                    197
#define IDB_TRIGGERC                    199
#define IDD_NEWMOVEMENT                 200
#define IDI_ICON3                       202
#define IDI_ICON4                       203
#define IDB_LAYER1                      208
#define IDB_EVENT2                      210
#define IDB_SYSTEMC                     211
#define IDC_CREATE                      212
#define IDD_ANGLE                       212
#define IDC_TEMPLATES                   213
#define IDB_HEADER                      213
#define IDC_PLATFORMS                   214
#define IDB_BITMAP5                     214
#define IDB_DISK                        214
#define IDB_BITMAP6                     215
#define IDB_INFOI                       215
#define IDR_MENUICONS                   217
#define IDD_DIALOG1                     218
#define IDD_FINDREPLACE                 218
#define IDB_BITMAP9                     222
#define IBR_LAYERTOOLBAR                224
#define IDD_DIALOG_PROPERTIES           226
#define IDC_COLOURS                     228
#define IDC_PALETTE                     229
#define IDB_BITMAP7                     229
#define IDB_NOTEQUAL                    230
#define IDC_ANIMATION                   230
#define IDI_ICON5                       231
#define IDR_ACCELERATOR2                232
#define IDB_SYSTEM                      236
#define IDD_ADDVARIABLE                 237
#define IDD_OBJECTSELECTOR              239
#define IDD_ADDTRAIT                    240
#define IDD_ATTRIBUTEMANAGER            240
#define IDB_ICONADD                     243
#define IDB_ICONDELETE                  244
#define IDB_ICONEDIT                    245
#define IDD_MANAGEVARIABLES             246
#define IDB_ICONSAVE                    247
#define IDB_ICONLOAD                    248
#define IDR_FRAMEIMAGE                  252
#define IDD_NEWTRANSITION               253
#define IDD_EXCHANGE                    254
#define IDB_BITMAP8                     255
#define IDB_CONSTRUCTICON               255
#define IDB_DEFAULTICON                 256
#define IDD_MANAGECONTROLS              260
#define IDD_MANAGE_ACTION_POINTS        261
#define IDD_MANAGE_IMAGE_POINTS         261
#define IDD_IMPORT_IMAGES               263
#define IDB_BITMAP1                     264
#define IDB_ANGLEICONS                  265
#define IDD_PICED_SETTINGS              273
#define IDD_ANIMATORBAR                 274
#define IDD_SCRIPT                      275
#define IDD_PROGRESSDLG                 276
#define IDD_UPDATE                      277
#define IDD_PYTHONLIBS                  279
#define IDR_PYTHONTOOLBAR               280
#define IDR_LAYERICONS                  282
#define IDB_BITMAP3                     283
#define IDB_RESOURCEICONS               283
#define IDI_SEARCH                      285
#define IDR_MAINWNDICON                 286
#define IDD_INSTALLER                   287
#define IDB_ANIMICONS                   289
#define ID_LAYER_LOCK                   290
#define ID_LAYER_HIDE                   291
#define IDB_UP                          291
#define IDD_FAMILYMANAGER               292
#define IDC_PAN_ALL                     293
#define IDC_PAN_DOWN                    294
#define IDC_PAN_DOWNFAST                295
#define IDC_PAN_DOWNLEFT                296
#define IDC_PAN_DOWNLEFTFAST            297
#define IDC_PAN_DOWNRIGHT               298
#define IDC_PAN_DOWNRIGHTFAST           299
#define IDC_PAN_LEFT                    300
#define IDC_PAN_LEFTFAST                301
#define IDC_PAN_LEFTRIGHT               302
#define IDC_PAN_RIGHT                   303
#define IDC_PAN_RIGHTFAST               304
#define IDC_PAN_SPIN                    305
#define IDC_PAN_UP                      306
#define IDC_PAN_UPDOWN                  307
#define IDC_PAN_UPFAST                  308
#define IDC_PAN_UPLEFT                  309
#define IDC_PAN_UPLEFTFAST              310
#define IDC_PAN_UPRIGHT                 311
#define IDC_PAN_UPRIGHTFAST             312
#define IDC_PICED_BRUSH                 313
#define IDC_PICED_CROSS                 314
#define IDC_PICED_ERASE                 315
#define IDC_PICED_FILL                  316
#define IDC_PICED_PEN                   317
#define IDC_SPLIT                       318
#define IDD_REMOVEFAMILYVAR             319
#define IDD_ADDFAMILYVARS               320
#define IDD_FMPRIVATEVARIABLES          321
#define IDD_SETTINGS                    323
#define IDB_BITMAP10                    326
#define IDB_UPARROW                     326
#define IDB_BITMAP11                    327
#define IDB_DOWNARROW                   327
#define ID_GRID                         329
#define ID_TRANSITIONS                  996
#define ID_VARIABLES                    997
#define ID_EVENTSHEETS                  998
#define ID_DEBUG                        999
#define ID_DEBUGLAYOUT                  1000
#define IDC_RADIO1                      1000
#define IDC_SPLITTER                    1000
#define IDC_AP_MOVE_INC                 1000
#define IDC_RADIO2                      1001
#define IDC_FPOINT                      1001
#define IDC_AP_MOVE_TOT                 1001
#define IDC_MAIN                        1001
#define IDC_RADIO3                      1002
#define IDC_PE_PEN                      1002
#define IDC_AP_ROTATE_INC               1002
#define IDC_TOOLS                       1002
#define IDC_CHECK1                      1003
#define IDC_HUE                         1003
#define IDC_PE_ERASER                   1003
#define IDC_AP_ROTATE_TOT               1003
#define IDC_RADIO8                      1003
#define IDC_SETTINGS                    1003
#define IDC_MIXERBAR                    1003
#define IDC_LIST1                       1004
#define IDC_SAT                         1004
#define IDC_PE_CROSS                    1004
#define IDC_AP_SCALE_INC                1004
#define IDC_RADIO4                      1005
#define IDC_CHECK3                      1005
#define IDC_CON                         1005
#define IDC_LUM                         1005
#define IDC_PE_CROSS_TAKE               1005
#define IDC_AP_SCALE_TOT                1005
#define IDC_LIST3                       1005
#define IDC_ADDED                       1005
#define IDC_ENABLEPYTHON                1005
#define IDC_RADIO5                      1006
#define IDC_BUTTON1                     1006
#define IDC_RED                         1006
#define IDC_COLOR                       1006
#define IDC_AP_DIM1                     1006
#define IDC_LAYER_ADD                   1006
#define IDC_DONE                        1006
#define IDC_COLOUR                      1006
#define IDC_CUT_INTO_TILES              1006
#define IDC_COPYDLL                     1006
#define IDC_GREEN                       1007
#define IDC_FONT                        1007
#define IDC_AP_DIM2                     1007
#define IDC_LAYER_DEL                   1007
#define IDC_HHELP                       1007
#define IDC_CHECK4                      1007
#define IDC_RADIO6                      1007
#define IDC_BUTTON3                     1007
#define IDC_INSTALLSETTINGS             1007
#define IDC_AUTHOR                      1008
#define IDC_DELETEITEM                  1008
#define IDC_LOADFROMFILE                1008
#define IDC_BLUE                        1008
#define IDC_LAYER_UP                    1008
#define IDC_CHECK5                      1008
#define IDC_DOWNLOAD                    1008
#define IDC_VERSION                     1009
#define IDC_PE_CROSS_COPY               1009
#define IDC_AP_MOVE_TOT_DIM2            1009
#define IDC_LAYER_DOWN                  1009
#define IDC_DOWN                        1009
#define IDC_INFO                        1010
#define IDC_DESC                        1010
#define IDC_AP_INSTANCE                 1010
#define IDC_LAYER_DUPLICATE             1010
#define IDC_BUTTON5                     1010
#define IDC_EDIT1                       1011
#define IDC_AP_DUPLICATE                1011
#define IDC_BUTTON7                     1011
#define IDC_EDIT2                       1012
#define IDC_REF                         1012
#define IDC_LAYER_MOREOPTIONS           1012
#define IDC_BUTTON8                     1012
#define IDC_FAMILYNAME                  1012
#define IDC_BUTTON9                     1013
#define IDC_BUTTON2                     1014
#define IDC_CLEAR                       1014
#define IDC_TOOLBOX                     1014
#define IDC_RELATIVE                    1014
#define IDC_RENAME                      1014
#define IDC_SWAP                        1014
#define IDC_PACKAGE                     1014
#define IDC_REMOVEVAR                   1014
#define IDC_TREE1                       1015
#define IDC_MENU                        1015
#define IDC_EDITNAME                    1015
#define IDC_ALL                         1015
#define IDC_PARAMTREE                   1015
#define IDC_HOTSPOTX                    1015
#define IDC_CLASSES                     1015
#define IDC_BUTTON4                     1015
#define IDC_MOVEUP                      1015
#define IDC_USER                        1016
#define IDC_ADDIMAGE                    1016
#define IDC_ZORDER                      1016
#define IDC_HOTSPOTY                    1016
#define IDC_MOVEDOWN                    1016
#define IDC_BUG                         1017
#define IDC_ADDIMAGE2                   1017
#define IDC_MANIPULATE                  1017
#define IDC_VARS                        1017
#define IDC_COMMENTCOLOUR               1018
#define IDC_ITEMTEXT                    1019
#define IDC_EDITITEM                    1020
#define IDC_INSERTITEM                  1021
#define IDC_SAVEIMAGE                   1022
#define IDC_EDITIMAGE                   1023
#define IDC_DELETEIMAGE                 1024
#define IDC_IMAGENAME                   1025
#define IDC_BITMAP                      1026
#define IDC_BLURS                       1028
#define IDC_EFFECTS                     1029
#define IDC_ROTATION                    1030
#define IDC_DISPLAY                     1031
#define IDC_SAVE                        1032
#define IDC_CANCEL                      1033
#define IDC_CLOSE                       1034
#define IDC_MESSAGE                     1039
#define IDC_RECT                        1040
#define IDC_MESSAGE2                    1040
#define IDC_ARGNUM                      1041
#define IDC_ARGDESC                     1042
#define IDC_PARAM                       1043
#define IDC_NEXT                        1044
#define IDC_BACK                        1045
#define IDC_FINISH                      1046
#define IDC_PARAMS                      1047
#define IDC_ADD                         1047
#define IDC_BBOX                        1048
#define IDC_NAMET                       1049
#define IDC_BUILD                       1050
#define IDC_DEFAULTS                    1051
#define IDC_MAIN_MENUBAR                1051
#define IDC_BROWSE                      1052
#define IDC_ACE                         1053
#define IDC_ACELIST                     1054
#define IDC_OBJNAME                     1055
#define IDC_COMMENT                     1056
#define IDC_TEXT                        1057
#define IDC_DESCRIPTION                 1057
#define IDC_AP_MOVEX_SPIN               1058
#define IDC_AP_MOVEY_SPIN               1059
#define IDC_AP_MOVEX                    1060
#define IDC_AP_MOVEY                    1061
#define IDC_AP_COUNT_DIM1               1062
#define IDC_AP_ROTATEX                  1063
#define IDC_AP_ROTATEX_SPIN             1064
#define IDC_AP_ROTATEY                  1065
#define IDC_AP_ROTATEY_SPIN             1066
#define IDC_AP_COUNT_DIM1_SPIN          1067
#define IDC_AP_SCALEX                   1068
#define IDC_AP_SCALEX_SPIN              1069
#define IDC_AP_SCALEY                   1070
#define IDC_AP_SCALEY_SPIN              1071
#define IDC_AP_COUNT_DIM2               1072
#define IDC_AP_COUNT_DIM2_SPIN          1073
#define IDC_AP_MOVEX_DIM2               1074
#define IDC_AP_MOVEX_DIM2_SPIN          1075
#define IDC_AP_MOVEY_DIM2               1076
#define IDC_AP_MOVEY_DIM2_SPIN          1077
#define IDC_AP_OBJECT_COUNT             1078
#define IDC_LAYER_DRAGLISTBOX           1079
#define IDC_LAYER_EFFECT                1080
#define IDC_BOX                         1080
#define IDC_GROUP                       1080
#define ID_PREVIEW                      1081
#define IDC_LANGUAGE                    1081
#define ID_PREVIEWLAYOUT                1082
#define IDC_LAYER_OBJLIST               1082
#define IDC_CHECKFORUPDATES             1082
#define IDC_MAXIMIZE                    1083
#define IDC_PRODUCTVERSION              1084
#define IDC_INFOTEXT                    1086
#define IDC_LIST2                       1087
#define IDC_CATEGORIES                  1087
#define IDC_HOTKEY                      1088
#define IDC_OBJECTS                     1089
#define IDC_OPTIONS                     1090
#define IDC_VALUE1                      1091
#define IDC_COMBO1                      1092
#define IDC_COMBO_PROPERTIES            1092
#define IDC_VALUE2                      1093
#define IDC_FUNCTIONS                   1093
#define IDC_FILTER                      1094
#define IDC_SLIDER1                     1095
#define IDC_ALPHA                       1096
#define IDC_APPNAME                     1097
#define IDC_INFORMATION                 1098
#define IDC_REMOVE                      1099
#define IDC_TESTERS                     1100
#define IDC_PEOPLE                      1101
#define IDC_GETMORE                     1102
#define IDC_EXPAND                      1103
#define IDC_STACK                       1104
#define IDC_STACKBORDER                 1104
#define IDC_LIST                        1105
#define IDC_EXT1                        1107
#define IDC_EXT2                        1108
#define IDC_EXT3                        1109
#define ID_PREFERENCES                  1110
#define IDC_SEARCH                      1116
#define IDC_FIND                        1117
#define IDC_RESULTS                     1118
#define IDC_TAB1                        1119
#define IDC_SEARCH2                     1119
#define IDC_REPLACEWITH                 1119
#define IDC_SEARCH3                     1120
#define IDC_REPLACE                     1120
#define IDC_UP                          1121
#define IDC_REPLACEALL                  1121
#define IDC_SELECTALL                   1122
#define IDC_TABS                        1123
#define IDC_FXDESC                      1123
#define IDC_PROPERTIES_TOOLBAR          1124
#define IDC_LIST_PROPERTIES             1125
#define IDC_STATIC_PROPERTY_FRAME       1126
#define IDC_ZOBJLIST                    1127
#define IDC_DELETE                      1130
#define IDC_STATICNAME                  1131
#define IDC_STATICPARAMS                1132
#define IDC_SEPARATOR                   1133
#define IDC_CHECKED                     1134
#define IDC_CHECKED2                    1135
#define IDC_VARIABLE                    1135
#define IDC_ENABLE                      1135
#define IDC_MANAGE                      1136
#define IDC_DISABLED                    1137
#define IDC_TITLE                       1138
#define IDC_SNAPTO                      1139
#define IDC_PROGRESS1                   1140
#define IDC_TIME                        1141
#define IDC_SPEEDLABEL                  1142
#define IDC_FRAMETIMELABEL              1145
#define IDC_NAMELABEL                   1146
#define IDC_CONTROLSLIST                1154
#define IDC_COMBO                       1155
#define IDC_COLOUR_MASK                 1168
#define IDC_FLIP                        1169
#define IDC_TILESETX                    1170
#define IDC_ROTATE1                     1171
#define IDC_ROTATE2                     1172
#define IDC_MIRROR                      1173
#define IDC_TILESETY                    1174
#define IDC_TILESETW                    1175
#define IDC_TILESETH                    1176
#define IDC_STATIC_X                    1177
#define IDC_STATIC_Y                    1178
#define IDC_STATIC_TILEW                1179
#define IDC_STATIC_TILEY                1180
#define IDC_STATIC_TILEH                1181
#define ID_CANCEL2                      1182
#define IDC_GROUP1                      1183
#define IDC_GROUP2                      1184
#define IDC_GROUP3                      1185
#define IDC_PREVIEW_IMAGE               1186
#define IDC_COLLISION                   1187
#define IDC_HOTSPOT1                    1188
#define IDC_HOTSPOT2                    1191
#define IDC_HOTSPOT3                    1192
#define IDC_ANGLES                      1192
#define IDC_HOTSPOT4                    1193
#define IDC_AUTOSAVE                    1193
#define IDC_HOTSPOT5                    1194
#define IDC_AUTOSAVE2                   1194
#define IDC_AUTOBACKUP                  1194
#define IDC_HOTSPOT6                    1195
#define IDC_ANIMATIONS                  1195
#define IDC_HOTSPOT7                    1196
#define IDC_FRAMES                      1196
#define IDC_HOTSPOT8                    1197
#define IDC_SCRIPT                      1197
#define IDC_HOTSPOT9                    1198
#define IDC_STATUS                      1198
#define IDC_VARIABLENAME                1201
#define IDC_PROGRESS                    1202
#define IDC_FILES                       1204
#define IDC_HELPLINE                    1205
#define IDC_NONE                        1206
#define IDC_INFOICON                    1207
#define IDC_TOOLBAR                     1208
#define IDC_EDITOR                      1209
#define IDC_TYPE                        1210
#define IDC_OICON                       1211
#define IDC_CONDITIONS                  1212
#define IDC_ACTIONS                     1213
#define IDC_S1T1                        1213
#define IDC_MODULES                     1214
#define IDC_S2T1                        1215
#define IDC_EXPORTPATH                  1216
#define IDC_RUNAFTER                    1217
#define IDC_INSTALLER                   1218
#define IDC_INSERT                      1218
#define IDC_INSERT2                     1219
#define IDC_SCREENSAVER                 1219
#define IDC_SNIPPETS                    1220
#define IDC_FULLSCREEN                  1221
#define IDC_LICENSE                     1222
#define IDC_OS                          1223
#define IDC_PATH                        1224
#define IDC_ROTATE                      1226
#define IDC_FAMILIES                    1228
#define IDC_NUMBACKUPS                  1229
#define IDC_AUTOBACKUPAUTOSAVE          1230
#define IDC_THEME                       1232
#define IDC_FAMILYVARS                  1233
#define IDC_ADDVAR                      1234
#define IDC_VARNAMEEDIT                 1235
#define IDC_VARSLIST                    1236
#define IDC_BOOKMARK                    1237
#define IDC_PROPSHEET                   1238
#define IDC_EDITPROFILES                1240
#define IDC_PROFILE                     1241
#define IDC_EDIT3                       1242
#define IDC_EDIT4                       1243
#define IDC_CHECK2                      1244
#define IDC_CHECK7                      1245
#define IDC_TITLELABEL                  1246
#define IDC_CHECK8                      1247
#define IDC_DESCRIPTIONLABEL            1247
#define IDC_LISTOBJECTS                 1248
#define IDC_FOLDER                      1249
#define IDC_STYLES                      1250
#define IDC_ADDSTYLE                    1251
#define IDTOPTEXT                       1901
#define IDAUTHOR                        1902
#define IDVERSION                       1903
#define IDAUTHOR2                       1903
#define IDINFO                          1904
#define IDAUTHOR3                       1904
#define IDDESCRIPTION                   1904
#define ID_INSERTC                      2018
#define ID_COMMENTCOLOUR                2019
#define IDR_ADDTOOLBAR                  2020
#define IDC_PAGE_FRAME                  11004
#define IDC_CAPTION_BAR                 11009
#define IDC_TREE_CTRL                   11010
#define IDC_PREFHELP                    11011
#define IDC_VISIBLE_CHK                 11015
#define IDC_FRAME_VIS_CHK               11016
#define IDC_FRAMEFILL_CHK               11019
#define IDC_FRACFILL_CHK                11033
#define IDC_NAME                        11039
#define IDC_INC                         11075
#define IDC_SCALE                       11076
#define IDR_DOCNAME                     11077
#define ID_FILL                         14465
#define ID_PICK                         14466
#define ID_ZOOM                         14467
#define ID_PEN                          14468
#define ID_BRUSH                        14469
#define ID_ARROW                        14470
#define ID_TEXT                         14471
#define ID_LINE                         14472
#define ID_RECTANGLE                    14473
#define ID_POLYGON                      14474
#define ID_SELECT_COLOR                 14475
#define ID_SELECT_POLYGON               14476
#define ID_SELECT_ELLIPSE               14478
#define ID_SELECT_RECTANGLE             14479
#define ID_ELLIPSE                      14480
#define ID_CUSTOMBRUSH                  14481
#define ID_TUBE                         14482
#define ID_SELECT_WAND                  14483
#define ID_SELECT_FREE                  14484
#define IDB_GUI_MDIICONS                18040
#define IDB_GUI_DOCKBAR                 18041
#define IDB_GUI_DOCKBAROFFICE           18042
#define ID_RIBBON_MOVEFORWARD           20545
#define ID_RIBBON_MOVEBACKWARD          20546
#define ID_RIBBON_GROUP                 20548
#define ID_RIBBON_UNGROUP               20549
#define ID_RIBBON_ADDTOGROUP            20550
#define ID_RIBBON_REMOVEFROMGROUP       20551
#define ID_RIBBON_SITEMAP               20552
#define ID_RIBBON_ADDCONDITION          20553
#define ID_RIBBON_ADDEVENT              20554
#define ID_RIBBON_ADDSUBEVENT           20555
#define ID_RIBBON_ADDGROUP              20556
#define ID_TOGGLEGRID                   20557
#define ID_EDITGRID                     20558
#define ID_SELECTALL                    20559
#define ID_UNSELECTALL                  20560
#define ID_ADDFRAME                     20561
#define ID_REMOVEFRAME                  20562
#define ID_ADDTRANSITION                20563
#define ID_GLOBVAR                      20564
#define ID_EVENTSHEET                   20565
#define ID_PLUGINS                      20566
#define ID_APPLICATION                  20567
#define ID_DX                           20568
#define ID_TEMPLATE                     20569
#define ID_MANAGEFAMILIES               20570
#define ID_GRID_SNAPMOVEMENT            20571
#define ID_GRID_SNAPRESIZE              20572
#define ID_RIBBON_FINDREPLACE           20573
#define ID_RIBBON_TOGGLEEVENT           20578
#define ID_RIBBON_ADDACTION             20579
#define ID_MANAGEOBJECTFOLDERS          20580
#define ID_MENU_FILES_WRITEINI          22923
#define ID_WRITEINI                     22923
#define ID_MENU_WINDOWS_SETWINDOWSTYLE  22924
#define ID_MENU_WINDOWS_SENDMESSAGE     22925
#define ID_MENU_WINDOWS_ANIMATEWINDOW   22926
#define ID_RESIZE                       22927
#define ID_SUBBY                        22929
#define ID_MENU_WINDOWS_MOVEWINDOW      22934
#define ID_MENU_WINDOWS_SHOWWINDOW      22935
#define IDC_WIDTH                       22992
#define IDC_WIDTH_PERCENTAGE            22993
#define IDC_HEIGHT                      22994
#define IDC_HEIGHT_PERCENTAGE           22995
#define IDC_STATIC2                     22996
#define IDC_SPLITTER1                   22996
#define IDC_STATIC_TILEX                22996
#define IDC_PROPORTIONAL                22997
#define IDC_STRETCH                     22998
#define IDD_PICED_RESIZE                22999
#define IDD_FILTER                      23000
#define IDD_TEMPLATE                    23001
#define IDD_USEDPLUGINS                 23005
#define IDD_NEWHLSL                     23006
#define IDD_NEWFAMILY                   23007
#define IDD_EGROUP                      23009
#define IDD_GRID                        23010
#define IDD_MANAGEFAMILIES              23013
#define IDD_EXPORTWIZARD                23014
#define IDD_SNIPPETS                    23015
#define IDD_POPUPROTATE                 23016
#define IDD_FMEFFECTS                   23017
#define IDD_FMBEHAVIORS                 23018
#define IDD_PROFILES                    23019
#define ID_PROJECT_PREFERENCES          29000
#define ID_PREFERENCES_RUNTIME          29001
#define ID_ZIPCOMPRESSION_E             29006
#define ID_PREFERENCES_INSTALLER        29007
#define ID_EDITOR_EVENTEDITOR           29011
#define ID_EDITOR_FRAMEEDITOR           29012
#define ID_EDITOR_SCRIPTEDITOR          29013
#define ID_EDIT_EVENTS                  29014
#define ID_EVENTS_VIEW                  29015
#define ID_EDITOR_EVENTVIEW             29016
#define ID_EDITOR_COPYEVENTSASSCRIPT    29020
#define ID_EDITOR_COPYEVENTSASSCRIPT29021 29021
#define ID_PROJECT_VERSIONEDITOR        29026
#define ID_EDIT_FINDANDREPLACE          29027
#define ID_EDIT_GOTO                    29028
#define ID_EDIT_FINDINPROJECT           29029
#define ID_BUILD_INSTALLER              29029
#define ID_EDITOR_INSERTBREAKPOINT      29030
#define ID_PROJECT_BUILD                29031
#define ID_BUILD_EXE                    29032
#define ID_TOOLBARS_DEBUG               29038
#define ID_TOOLBARS_ZOOM                29039
#define ID_EDITOR_REMOVEBREAKPOINT      29043
#define ID_INSTALLER_SETTINGS29044      29044
#define ID_RUNTIME_SOFTWARE29045        29045
#define ID_ZOOM_CUSTOM29046             29046
#define ID_EDIT_ARRAYPASTE29047         29047
#define ID_HELP_SCIRRA29048             29048
#define ID_EVENTVIEW_CHANGEALLTO        29049
#define ID_EDITOR_BREAKPOINTS           29053
#define ID_BREAKPOINTS_DISABLEBREAKPOINT 29054
#define ID_CHANGEALLTO_LIST             29055
#define ID_EDITOR_INSERTCOMMENT         29059
#define ID_COPYEVENTSASSCRIPT_CONDITIONS 29061
#define ID_EDITOR_CONDITIONS            29062
#define ID_CONDITIONS_INSERTCONDITION29065 29065
#define ID_FILE_EXIT                    29066
#define ID_PROJECT_HIERARCHY            29067
#define ID_TOOLBARS_COMMENT             29068
#define ID_PROJECT_COLLABORATION        29069
#define ID_COLLABORATION_USERS          29073
#define ID_EDITOR_MARKASREAD            29077
#define ID_Menu                         29079
#define ID_PROJECT_DEBUGSETTINGS        29081
#define ID_FILE_CLOSEALLPROJECTS        29082
#define ID_FILE_EXIT29083               29083
#define ID_FILE_SAVEALL                 29084
#define ID_VIEW_FORWARD                 29086
#define ID_VIEW_BOOKMARKS               29087
#define ID_PROJECT_SETASSTARTUPPROJECT  29089
#define ID_FILE_SAVEIT                  29091
#define ID_FILE_SAVEAS                  29092
#define ID__EFFECTS                     29093
#define ID_EFFECTS_NEWEFFECT            29094
#define ID_WINDOW_APPEARANCE            29098
#define ID_APPEARANCE_2007OBSIDIAN      29104
#define ID__TRAITS                      29110
#define ID__TRAITS29111                 29111
#define IDENTER                         29113
#define IDFR_PREVIEW                    29117
#define ID_MENU_GLOBAL                  29118
#define ID_MENU_GLOBAL29119             29119
#define ID_GLOBAL_CHANGEVARIABLE        29120
#define ID_MENU_CHANGEVALUE             29121
#define ID_MENU_GROUPACTIVATION         29122
#define ID_CHANGEGLOBALVARIABLE_MODIFY  29123
#define ID_CHANGEGLOBALVARIABLE_SET     29124
#define ID_CHANGEGLOBALVARIABLE_ADD     29125
#define ID_CHANGEGLOBALVARIABLE_SUBTRACT 29126
#define ID_RUNTIME_NEXTFRAME            29127
#define ID_RUNTIME_PREVIOUSFRAME        29128
#define ID_MENU_FRAMES                  29129
#define ID_FRAMES_RESTARTFRAME          29133
#define ID_FRAMES_RESTARTAPPLICATION    29134
#define ID_FRAMES_CANCELCLOSE           29136
#define ID_MENU_CREATION                29137
#define ID_CREATION_DUPLICATEOBJECT     29139
#define ID_CREATION_SHOOTOBJECTFROMOBJECT 29140
#define ID_MENU_RUNTIM                  29142
#define ID_MENU_NEW                     29155
#define ID_NEW_EVERYXFRAMES             29157
#define ID_NEW_EVERYXMILLISECONDS       29158
#define ID_NEW_COMPARETOXFRAMES         29159
#define ID_NEW_COMPARETOXMILLISECONDS   29160
#define ID_NEW_VALUEISSTRING            29161
#define ID_NEW_VALUEISINTEGER           29162
#define ID_NEW_VALUEISFLOAT             29163
#define ID_NEW_VALUEISNUMBER            29164
#define ID_NEW_RUNONCE                  29165
#define ID_NEW_LIMITEVENTTOONLYRUNXTIMES 29166
#define ID_NEW_RUNONCEEACHCYCLE         29167
#define ID_MENU_TIMER                   29170
#define ID_MENU_LOOPS                   29171
#define ID_MENU_VARIABLES               29172
#define ID_MENU_POINTCOLLISIONS         29175
#define ID_BUTTON29178                  29178
#define ID_MENU_EVENTSHEETEDITOR        29182
#define ID_MENU_LAYOUTEDITOR            29183
#define ID__CLONELAYOUT                 29184
#define ID_CLONELAYOUT                  29185
#define ID__NEWEVENT                    29186
#define ID_MENU_MOUSE                   29187
#define ID_MENU_LOOPS29188              29188
#define ID_MENU_FORMATDECIMAL           29193
#define ID_MENU_ZEROPAD                 29194
#define ID_MENU_NEWLINE                 29195
#define ID_MENU_LEFT                    29196
#define ID_MENU_RIGHT                   29197
#define ID_MENU_MID                     29198
#define ID_MENU_UPPERCASE               29199
#define ID_MENU_LOWERCASE               29200
#define ID_MENU_FIND                    29201
#define ID_MENU_REMOVE                  29202
#define ID_MENU_REPLACE                 29203
#define ID_MENU_TRIM                    29204
#define ID_MENU_REVERSE                 29205
#define ID_MENU_NUMTOKENS               29206
#define ID_MENU_GETTOKEN                29207
#define ID_MENU_DISTANCE                29208
#define ID_MENU_ANGLE                   29209
#define ID_MENU_COUNTINGMATCH           29210
#define ID_MENU_SCROLLX                 29211
#define ID_MENU_SCROLLY                 29212
#define ID_MENU_WINDOWWIDTH             29213
#define ID_MENU_WINDOWHEIGHT            29214
#define ID_MENU_LIMITS                  29215
#define ID_MENU_CONVERT                 29216
#define ID_MENU_TEXT                    29217
#define ID_MENU_MATHS                   29218
#define ID_MENU_TOKENS                  29219
#define ID_MENU_WINDOW                  29220
#define ID_MENU_EVENTS                  29221
#define ID_MENU_COLORS                  29222
#define ID_MENU_TIME                    29224
#define ID_MENU_CONVERT29225            29225
#define ID_MATHS_ROUNDING               29227
#define ID_SCROLLING_SETZOOM            29229
#define ID_SCROLLING_LAYERS             29230
#define ID_MENU_LAYERS                  29231
#define ID_LAYERS_SETSCROLLXRATIO       29232
#define ID_LAYERS_SETSCROLLYRATIO       29233
#define ID_LAYERS_SETZOOMRATIO          29234
#define ID_LAYERS_SETSCROLLXOFFSET      29235
#define ID_LAYERS_SETSCROLLYOFFSET      29236
#define ID_LAYERS_SETZOOMOFFSET         29237
#define ID_LAYERS_SHOW                  29238
#define ID_LAYERS_HIDE                  29239
#define ID_SCROLLING_LAYERS29240        29240
#define ID_LAYERS_SETFILTER             29241
#define ID_ISCLOSING                    29243
#define ID_VIEWVRAM                     29245
#define ID_HIDEALL                      29247
#define ID_LAYOUTEDITOR                 29250
#define ID_SHEETEDITOR                  29251
#define ID__P                           29254
#define ID_MENU_DIRECTX9RUNTIME         29255
#define ID_MENU_MENU                    29256
#define ID_DISPLAY_GETYBOTTOMOFVISIBLESCREEN 29257
#define ID_MENU                         29258
#define ID_MENU_                        29259
#define ID_MENU_ADDLAYOUT               29260
#define ID_MENU_REMOVELAYOUT            29261
#define ID_MENU_ADDLAYOUTDOWN           29262
#define ID_LAYER_UP                     29263
#define ID_LAYER_DOWN                   29264
#define ID_LAYERS_SHOWBOX               29265
#define IDC_AP_MOVE_INC_DIM2            29266
#define IDC_CHECK6                      29267
#define ID_EDIT_FINDANDREPLACE2         29275
#define ID_EXPORT_EXE                   32772
#define ID_FILE_EXPORT_ASSCREENSAVER    32773
#define ID_FILE_EXPORT_ASINTERNETAPP    32774
#define ID_VIEW_OBJECT                  32775
#define ID_FILE_NEW_TEMPLATE            32776
#define ID_INSERT_STRING                32777
#define ID_INSERT_ACTIVE                32778
#define ID_INSERT_BACKDROP              32779
#define ID_APP_PREF                     32786
#define ID_NEWOBJ                       32787
#define ID_VIEW_SIDEBAR                 32788
#define ID_APP_INSERT                   32789
#define ID_APPLICATION_FRAMEEDITOR      32790
#define ID_APPLICATION_EVENTEDITOR      32791
#define ID_FOO                          32792
#define ID_DELETEFRAME                  32793
#define ID_DELOBJ                       32794
#define ID_APP_FOO                      32796
#define MENU_EXPORTEXE                  32797
#define ID_HELP_REPORTBUG               32798
#define ID_INSERT_COMMENT               32800
#define ID_EDITMENU                     32802
#define ID_IMAGEBANK                    32804
#define ID_INSERT_FRAME                 32818
#define ID_ADD_FRAME                    32818
#define ID_MENU_VISITURL                32829
#define ID_EXPAND                       32836
#define ID_EDIT_DELETE                  32891
#define ID_EDIT_CLONE                   32892
#define ID_EDIT_DUPLICATE               32893
#define ID_EDIT_SELECTALL               32894
#define ID_EDIT_UNSELECT                32895
#define ID_EDIT_INVERTSELECTION         32896
#define ID_EDIT_PROPERTIES              32897
#define ID_VIEW_LAYERBAR                32898
#define ID_VIEW_PROPERTIESBAR           32899
#define ID_VIEW_RESOURCEBAR             32900
#define ID_EXCHANGE                     32901
#define ID_VIEW_ANIMBAR                 32902
#define ID_VIEW_OBJECTBAR               32903
#define ID_EXITC                        32910
#define ID_HOTSPOT                      32948
#define ID_ACTIONPOINT                  32949
#define ID_NEW                          32950
#define ID_OPEN                         32951
#define ID_SAVE                         32952
#define ID_SETUP                        32953
#define ID_CUT                          32954
#define ID_COPY                         32955
#define ID_PASTE                        32956
#define ID_DELETE                       32957
#define ID_UNDO                         32958
#define ID_SNIPPETS                     32959
#define ID_REDO                         32960
#define ID_MIRROR                       32961
#define ID_FLIP                         32962
#define ID_ROTATE                       32963
#define ID_CROP                         32964
#define ID_ERASOR                       32966
#define ID_MENU_RUNTIME_ENDAPPLICATION  32968
#define ID_APPLICATION_SCRIPTEDITOR     32970
#define ID_APPLICATION_VIEWUSEDPLUGINS  32971
#define ID__OBJECTINFORMATION           32972
#define ID_FILE_EXPORT_ASINSTALLER      32981
#define ID_EDIT_ARRAYPASTE              32984
#define ID_VIEW_ZOOM                    32987
#define ID_HELP_SCIRRA                  32995
#define ID_VIEW_OBJECTINFORMATION       32996
#define ID_EDITOR_INSERTOBJECT          32997
#define ID_EDITOR_INSERTCONDITION       32998
#define ID_MENU_INSERTLAYOUT            33815
#define ID_MENU_DELETELAYOUT            33816
#define IDFR_INSERT                     33900
#define IDFR_INSERTTAG                  33901
#define IDFR_IMAGEBANK                  33902
#define IDFR_CUT                        33910
#define IDFR_COPY                       33911
#define IDFR_PASTE                      33912
#define IDFR_DELETE                     33913
#define IDFR_ARRAYPASTE                 33914
#define IDFR_LOCKUNSELECTED             33920
#define IDFR_LOCKSELECTED               33921
#define IDFR_HIDESELECTED               33923
#define IDFR_HIDEUNSELECTED             33924
#define IDFR_UNHIDEALL                  33925
#define IDFR_ORDERFRONT                 33930
#define IDFR_ORDERBACK                  33931
#define IDFR_ORDERFORWARD               33932
#define IDFR_ORDERBACKWARD              33933
#define IDFR_ORDERX                     33934
#define IDFR_ORDERY                     33935
#define IDFR_PASTECLONE                 33936
#define IDFR_ORDERID                    33937
#define IDFR_ORDERDIALOG                33938
#define IDFR_ADDTOGROUP                 33939
#define IDFR_ALIGNLEFT                  33940
#define IDFR_ALIGNCENTER                33941
#define IDFR_ALIGNRIGHT                 33942
#define IDFR_ALIGNTOP                   33943
#define IDFR_ALIGNMIDDLE                33944
#define IDFR_ALIGNBOTTOM                33945
#define IDFR_REMFROMGROUP               33946
#define IDFR_FRAME_ALIGNLEFT            33950
#define IDFR_FRAME_ALIGNRIGHT           33951
#define IDFR_FRAME_ALIGNCENTER          33952
#define IDFR_FRAME_ALIGNTOP             33953
#define IDFR_FRAME_ALIGNMIDDLE          33954
#define IDFR_FRAME_ALIGNBOTTOM          33955
#define IDFR_DISTRIBUTEH                33960
#define IDFR_DISTRIBUTEV                33961
#define IDFR_SAMEWIDTH                  33970
#define IDFR_SAMEHEIGHT                 33971
#define IDFR_SAMESIZE                   33972
#define IDFR_OBJECTINFORMATION          33974
#define IDFR_SHOWTAGS                   33975
#define IDFR_HIDETAGS                   33976
#define IDFR_LOCKLAYER                  33977
#define IDFR_HIDELAYER                  33978
#define IDFR_DEFAULTGRID                33979
#define IDFR_GROUP                      33980
#define IDFR_UNGROUP                    33981
#define IDFR_NEWMOVEMENT                33982
#define IDFR_CLOSEGROUP                 33983
#define IDFR_REMOVEALLMOVEMENTS         33984
#define IDFR_REMOVEALLEFFECTS           33985
#define IDFR_UNLOCKALL                  33986
#define IDFR_OPENGROUP                  33987
#define IDFR_CENTERFRAME                33990
#define IDFR_CENTERFRAMEOVERSELECTION   33991
#define IDFR_NEWEFFECT                  33992
#define ID_CODE                         34222
#define IDC_OBJECTLIST                  34223
#define IDD_PROPERTY_PAGE_3             34224
#define IDB_SYSTEMB                     34225
#define IDC_BOX1                        34226
#define IDC_BOX2                        34227
#define IDDESC                          34228
#define IDC_ANGLE                       35001
#define IDAPPLY                         45578
#define ID_DEBUG_START                  45579
#define ID_DEBUG_PAUSE                  45580
#define ID_DEBUG_STOP                   45581

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        329
#define _APS_NEXT_COMMAND_VALUE         29287
#define _APS_NEXT_CONTROL_VALUE         1252
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
